apiVersion: v1
kind: Service
metadata:
  name: fc3-desafio-03-nest-srv
spec:
  selector:
    app: fc3-desafio-03-nest
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc3-desafio-03-nest-depl
  labels:
    app: fc3-desafio-03-nest-depl
spec:
  replicas: 1
  template:
    metadata:
      name: fc3-desafio-03-nest
      labels:
        app: fc3-desafio-03-nest
    spec:
      containers:
        - name: fc3-desafio-03-nest
          image: wdot456/fc3-desafio-03:nest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: fc3-desafio-03-nest
