apiVersion: v1
kind: Service
metadata:
  name: fc3-desafio-03-react-srv
spec:
  selector:
    app: fc3-desafio-03-react
  ports:
    - port: 3001
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc3-desafio-03-react-depl
  labels:
    app: fc3-desafio-03-react-depl
spec:
  replicas: 1
  template:
    metadata:
      name: fc3-desafio-03-react
      labels:
        app: fc3-desafio-03-react
    spec:
      containers:
        - name: fc3-desafio-03-react
          image: wdot456/fc3-desafio-03:react
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: fc3-desafio-03-react
